dist: xenial
language: c
os: linux
git:
  quiet: true
addons:
  apt:
    config:
      retries: true
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - libffi-dev
      - libgdbm-dev
      - libgmp-dev
      - libjemalloc-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - openssl
      - valgrind
      - zlib1g-dev
matrix:
  include:
    - name: x86_64-linux
      os: linux
      compiler: gcc-8
install: true
script: scripts/run.sh
branches:
  only:
    - master
